version: 2
jobs:
  build:
    working_directory: ~/sora-android-sdk
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx1600m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sora-android-sdk/build.gradle" }}
      - run:
          name: Create "gradle.properties"
          command: cp gradle.properties.example gradle.properties
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sora-android-sdk/build.gradle" }}
      - run:
          name: Run lint & build
          command: ./gradlew testDebug lint assembleRelease assembleDebug
      - store_artifacts:
          path: sora-android-sdk/build/outputs
          destination: outputs
      - store_artifacts:
          path: sora-android-sdk/build/reports
          destination: reports
