[versions]
# Build tools
android-gradle-plugin = "8.11.1"
kotlin = "2.0.20"
dokka = "1.9.20"
ktlint-gradle = "12.1.1"
versions-plugin = "0.46.0"
android-maven-plugin = "2.1"

# Android
compileSdk = "36"
minSdk = "21" 
targetSdk = "36"

# Java/JVM
jvmTarget = "1.8"
javaCompatibility = "1.8"

# Libraries
libwebrtc = "140.7339.2.2"
gson = "2.13.1"
okhttp = "4.12.0"
kotlinx-coroutines = "1.9.0"
rxjava2 = "2.2.21"
rxandroid2 = "2.1.1"
rxkotlin2 = "2.4.0"

# Test libraries
junit = "4.13.2"
androidx-test-core = "1.6.1"
robolectric = "4.15.1"

[libraries]
# Kotlin BOM
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }

# Build tools
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
ktlint-gradle-plugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-gradle" }
ben-manes-versions-plugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versions-plugin" }
android-maven-gradle-plugin = { module = "com.github.dcendents:android-maven-gradle-plugin", version.ref = "android-maven-plugin" }

# Main libraries
shiguredo-webrtc-android = { module = "com.github.shiguredo:shiguredo-webrtc-android", version.ref = "libwebrtc" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava2" }
rxandroid2 = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid2" }
rxkotlin2 = { module = "io.reactivex.rxjava2:rxkotlin", version.ref = "rxkotlin2" }

# Test libraries
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-maven = { id = "com.github.dcendents.android-maven", version.ref = "android-maven-plugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }

[bundles]
reactive = ["rxjava2", "rxandroid2", "rxkotlin2"]
testBase = ["junit", "androidx-test-core", "kotlin-test-junit"]

